In [1]:
#import the libraries
import pandas as pd
import numpy as np
from scipy import stats

## Super Market example







In [2]:
1-(stats.t.cdf(2.2,df=79))

np.float64(0.015364507770762481)

# Call Center example

In [3]:
# Call center example
# 1st way
p2=1-stats.t.cdf(1.4,49)
p=p2*2
p

np.float64(0.16781331091681295)

In [4]:
# Call center example
# 2nd way
p1=stats.t.cdf(-1.4,49)
p=p1*2
p

np.float64(0.16781331091681306)

In [5]:
# Call center example

# 3rd way
p=2*stats.t.cdf(-1.4,49)
print(p)
#print(round(r,4))
print("Rounded Value=",round(p,4))


0.16781331091681306
Rounded Value= 0.1678


In [6]:
import numpy as np
from scipy import stats
# to calculate t value
t=(7.2-4)/(3/np.sqrt(50)) # t value for x bar=4.6, mu=4, s=3, n=50
t

np.float64(7.542472332656508)

In [7]:
p=2*stats.t.cdf(-7.5424,49)
p

np.float64(9.62851076804498e-10)

# One tail test

In [8]:
# Ice-cream factory example
import pandas as pd
from scipy import stats
data=pd.Series([0.593, 0.142, 0.329, 0.691, 0.231, 0.793, 0.519, 0.392, 0.418])


In [9]:
data

0    0.593
1    0.142
2    0.329
3    0.691
4    0.231
5    0.793
6    0.519
7    0.392
8    0.418
dtype: float64

In [10]:
stats.ttest_1samp(data,0.3) # population mean = 0.3, this method always give you 2 tail p-value
# t-value=2.2050588385131595 and pvalue=0.05853032968489765 here, p = p1+p2
# index of t-value is 0 and p-value is 1

TtestResult(statistic=np.float64(2.2050588385131595), pvalue=np.float64(0.05853032968489765), df=np.int64(8))

In [11]:

p=stats.ttest_1samp(data,0.3)[1] # mu=0.3, index of p-value is 1, so [1] is given
# pvalue=0.05853032968489765 here, p = p1+p2
p

np.float64(0.05853032968489765)

In [12]:
#As this is a one tail test p value so divide by 2 to get final p-value
p_value= p/2
p_value
# Null Hypo. is Mu<=0.3, Alter. Hypo. is Mu>0.3,
# Alfa = 0.05, P-value we got is 0.029 So p<alfa. So reject Null Hypo.
# So go for Alt. Hypo.
# interpret it: As mean value Mu >0.3 factory is causing problem.

np.float64(0.029265164842448826)

# Two Sample Two Tail test - From scipy - stats.ttest_ind(sample1, sample2)

In [13]:
# 2-Sample 2-tail test
# comparing drugs - Control group and treatment group
Control=pd.Series([91, 87, 99, 77, 88, 91])
Treat =pd.Series([101, 110, 103, 93, 99, 104])

In [14]:
stats.ttest_ind(Control,Treat) # two tail independent
# p=p1+p2. We are conducting 2 sample 2 tail test, so no need to divide p by 2.
# p=0.006, alfa=0.05, p<alfa so reject null hypo. so accept alt. Hypo
# interpretation: 2 responses are not equal so drug is working.

TtestResult(statistic=np.float64(-3.4456126735364876), pvalue=np.float64(0.006272124350809803), df=np.float64(10.0))

# 2 Proportion t-Test - From statsmodels.api - stats.ttest_ind(proportion1, proportion2)

In [15]:
import numpy as np

In [16]:
#Data: Placement Data example

n1 = 247
p1 = .37 # proportion is 0.37

n2 = 308
p2 = .39 # proportion is 0.39

In [17]:
sample1 = np.random.binomial(1, p1, n1) # 1 - placed i.e. probability of success, 0-not placed

In [18]:
sample1 # 247 student's data. 0-not placed, 1-placed

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0])

In [19]:
len(sample1)

247

In [20]:
sample1.mean()

np.float64(0.3522267206477733)

In [21]:
sample2 = np.random.binomial(1, p2, n2) # as its a random function every time you execute, you will get diff ans.

In [22]:
sample2

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [23]:
len(sample2)

308

In [24]:
sample2.mean()

np.float64(0.3474025974025974)

In [25]:
import statsmodels.api as sm # two proportion test function is available in statsmodels.api only
p=sm.stats.ttest_ind(sample1, sample2)[1]# 2 sample, 2 tail test. Middle is the p-value
# p>0.05 so accept null hypo.
# interpretation: students are almost equally got placed in 2 states.
# i.e. no significant difference in providing placement opportunities to students in 2 states.
print(p)
print(round(p,3))

0.9059222868625867
0.906


In [26]:
a=0.05
if p>a:
  print(f'Accept null hypothesis.\n--------------------------')
else:
  print(f'Accept alternativ hypothesis.\n-------------------')

Accept null hypothesis.
--------------------------


In [27]:
import statsmodels.api as sm

a=0.05 # alpha

sample1 = np.random.binomial(1, p1, n1)
sample2 = np.random.binomial(1, p2, n2)

p=sm.stats.ttest_ind(sample1, sample2)[1]
print(p)
print(round(p,3))
if p>a:
  print(f'Accept null hypothesis.\n--------------------------')
else:
  print(f'Accept alternativ hypothesis.\n-------------------')

0.84937167825166
0.849
Accept null hypothesis.
--------------------------


In [34]:
n1 = 10
p1 = 0.84 # proportion is 0.84

n2 = 10
p2 = .6

sample1 = np.random.binomial(1, p1, n1)
print(sample1)
print(sample1.mean())
sample2 = np.random.binomial(1, p2, n2)
print(sample2)
print(sample2.mean())

[1 1 0 1 1 1 1 1 1 1]
0.9
[0 0 0 1 1 1 0 1 0 0]
0.4
